-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 09:01:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mmm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mmm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmm` DEFAULT CHARACTER SET utf8mb4 ;
USE `mmm` ;

-- -----------------------------------------------------
-- Table `mmm`.`mbti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`mbti` (
  `mbti_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mbti_name` ENUM('EI', 'NS', 'TF', 'JP', 'MINT', 'PINE', 'DIE') NULL DEFAULT NULL,
  PRIMARY KEY (`mbti_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`question` (
  `mbti_id` INT(11) NULL DEFAULT NULL,
  `question_id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `image_src` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `FKsgama42eg5wrly2e4qdd7ic3p` (`mbti_id` ASC) VISIBLE,
  CONSTRAINT `FKsgama42eg5wrly2e4qdd7ic3p`
    FOREIGN KEY (`mbti_id`)
    REFERENCES `mmm`.`mbti` (`mbti_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`answer` (
  `answer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `image_src` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `FK8frr4bcabmmeyyu60qt7iiblo` (`question_id` ASC) VISIBLE,
  CONSTRAINT `FK8frr4bcabmmeyyu60qt7iiblo`
    FOREIGN KEY (`question_id`)
    REFERENCES `mmm`.`question` (`question_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`mukjuk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`mukjuk` (
  `mukjuk_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `context` VARCHAR(255) NULL DEFAULT NULL,
  `image_src` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`mukjuk_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`mukgroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`mukgroup` (
  `is_solo` BIT(1) NULL DEFAULT NULL,
  `mukgroup_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `mukjuk_id` BIGINT(20) NULL DEFAULT NULL,
  `image_src` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`mukgroup_id`),
  INDEX `FKdpn0edvl1ifjlohm2uqb9jny7` (`mukjuk_id` ASC) VISIBLE,
  CONSTRAINT `FKdpn0edvl1ifjlohm2uqb9jny7`
    FOREIGN KEY (`mukjuk_id`)
    REFERENCES `mmm`.`mukjuk` (`mukjuk_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`food_recommend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`food_recommend` (
  `food_recommend_id` INT(11) NOT NULL AUTO_INCREMENT,
  `has_value` BIT(1) NULL DEFAULT NULL,
  `recommend_date` DATE NULL DEFAULT NULL,
  `mukgroup_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`food_recommend_id`),
  INDEX `FK12pyu6p8dg5h0hc3l425u2xhp` (`mukgroup_id` ASC) VISIBLE,
  CONSTRAINT `FK12pyu6p8dg5h0hc3l425u2xhp`
    FOREIGN KEY (`mukgroup_id`)
    REFERENCES `mmm`.`mukgroup` (`mukgroup_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`users` (
  `is_recorded` BIT(1) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nickname` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`mukbo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`mukbo` (
  `mukbo_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `mukgroup_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` ENUM('HUMAN', 'MUKBOT', 'DELETED') NULL DEFAULT NULL,
  PRIMARY KEY (`mukbo_id`),
  UNIQUE INDEX `UK_41xolf9w4a7u89inigjn6ayao` (`user_id` ASC) VISIBLE,
  INDEX `FKjgwp3asefwmyen68o206oikgq` (`mukgroup_id` ASC) VISIBLE,
  CONSTRAINT `FKjgwp3asefwmyen68o206oikgq`
    FOREIGN KEY (`mukgroup_id`)
    REFERENCES `mmm`.`mukgroup` (`mukgroup_id`),
  CONSTRAINT `FKoegmme2ym52ci8xaoyi0kbptd`
    FOREIGN KEY (`user_id`)
    REFERENCES `mmm`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`eaten_mukbo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`eaten_mukbo` (
  `food_recommend_id` INT(11) NULL DEFAULT NULL,
  `eaten_mukbo_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `mukbo_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`eaten_mukbo_id`),
  INDEX `FKc082mcdyhn2ch1a1k0858kdku` (`food_recommend_id` ASC) VISIBLE,
  INDEX `FKtfoy2x01s0drcha5wdlkl94b1` (`mukbo_id` ASC) VISIBLE,
  CONSTRAINT `FKc082mcdyhn2ch1a1k0858kdku`
    FOREIGN KEY (`food_recommend_id`)
    REFERENCES `mmm`.`food_recommend` (`food_recommend_id`),
  CONSTRAINT `FKtfoy2x01s0drcha5wdlkl94b1`
    FOREIGN KEY (`mukbo_id`)
    REFERENCES `mmm`.`mukbo` (`mukbo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`food_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`food_category` (
  `food_category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`food_category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`food` (
  `food_category_id` INT(11) NULL DEFAULT NULL,
  `food_id` INT(11) NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`food_id`),
  INDEX `FKpnfa6f8ubf600psx2mhefa1a1` (`food_category_id` ASC) VISIBLE,
  CONSTRAINT `FKpnfa6f8ubf600psx2mhefa1a1`
    FOREIGN KEY (`food_category_id`)
    REFERENCES `mmm`.`food_category` (`food_category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 98
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`food_mbti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`food_mbti` (
  `food_id` INT(11) NULL DEFAULT NULL,
  `food_mbti_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mbti_id` INT(11) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`food_mbti_id`),
  INDEX `FKlu2oferjbmsyhdtw1o65h7pbc` (`food_id` ASC) VISIBLE,
  INDEX `FKpc8mu9h1te84rbxdet5ns99d9` (`mbti_id` ASC) VISIBLE,
  CONSTRAINT `FKlu2oferjbmsyhdtw1o65h7pbc`
    FOREIGN KEY (`food_id`)
    REFERENCES `mmm`.`food` (`food_id`),
  CONSTRAINT `FKpc8mu9h1te84rbxdet5ns99d9`
    FOREIGN KEY (`mbti_id`)
    REFERENCES `mmm`.`mbti` (`mbti_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 389
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`weather`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`weather` (
  `weather_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`weather_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`food_weather`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`food_weather` (
  `food_id` INT(11) NULL DEFAULT NULL,
  `food_weather_id` INT(11) NOT NULL AUTO_INCREMENT,
  `weather_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`food_weather_id`),
  UNIQUE INDEX `UK_94wf24r3ukau95i4x4oxlbaqs` (`food_id` ASC) VISIBLE,
  INDEX `FK6psf3pplp8t0irld8rhihhwyq` (`weather_id` ASC) VISIBLE,
  CONSTRAINT `FK6psf3pplp8t0irld8rhihhwyq`
    FOREIGN KEY (`weather_id`)
    REFERENCES `mmm`.`weather` (`weather_id`),
  CONSTRAINT `FKoxn96b0fctu4q8ouywuybtd6l`
    FOREIGN KEY (`food_id`)
    REFERENCES `mmm`.`food` (`food_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`mukgroup_mukjuk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`mukgroup_mukjuk` (
  `mukgroup_id` BIGINT(20) NULL DEFAULT NULL,
  `mukgroup_mukjuk_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `mukjuk_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`mukgroup_mukjuk_id`),
  INDEX `FKfo38qs9s4h9yp6rcr064w3n1b` (`mukgroup_id` ASC) VISIBLE,
  INDEX `FKh6ghguc8j0wj7h1a9qxode080` (`mukjuk_id` ASC) VISIBLE,
  CONSTRAINT `FKfo38qs9s4h9yp6rcr064w3n1b`
    FOREIGN KEY (`mukgroup_id`)
    REFERENCES `mmm`.`mukgroup` (`mukgroup_id`),
  CONSTRAINT `FKh6ghguc8j0wj7h1a9qxode080`
    FOREIGN KEY (`mukjuk_id`)
    REFERENCES `mmm`.`mukjuk` (`mukjuk_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`muklog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`muklog` (
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `mukgroup_id` BIGINT(20) NULL DEFAULT NULL,
  `muklog_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`muklog_id`),
  INDEX `FKc6u9vwj2wn7w0lelcyaqkbypq` (`mukgroup_id` ASC) VISIBLE,
  CONSTRAINT `FKc6u9vwj2wn7w0lelcyaqkbypq`
    FOREIGN KEY (`mukgroup_id`)
    REFERENCES `mmm`.`mukgroup` (`mukgroup_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`recommended_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`recommended_food` (
  `eaten` BIT(1) NULL DEFAULT NULL,
  `food_id` INT(11) NULL DEFAULT NULL,
  `food_recommend` INT(11) NULL DEFAULT NULL,
  `recommended_food_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category` ENUM('NORMAL', 'NEW', 'WEATHER') NULL DEFAULT NULL,
  PRIMARY KEY (`recommended_food_id`),
  INDEX `FKbw7atpim55jahiupi8i4lca6r` (`food_id` ASC) VISIBLE,
  INDEX `FK8ol2ms5ugtd9b6w991g4r8qm` (`food_recommend` ASC) VISIBLE,
  CONSTRAINT `FK8ol2ms5ugtd9b6w991g4r8qm`
    FOREIGN KEY (`food_recommend`)
    REFERENCES `mmm`.`food_recommend` (`food_recommend_id`),
  CONSTRAINT `FKbw7atpim55jahiupi8i4lca6r`
    FOREIGN KEY (`food_id`)
    REFERENCES `mmm`.`food` (`food_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mmm`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmm`.`result` (
  `mbti_id` INT(11) NULL DEFAULT NULL,
  `result_id` INT(11) NOT NULL AUTO_INCREMENT,
  `score` INT(11) NULL DEFAULT NULL,
  `mukbo_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`result_id`),
  INDEX `FKmtoxyhettye5oke0c800xjo0l` (`mbti_id` ASC) VISIBLE,
  INDEX `FKbkpe37r7hqrg6uu6mpocklqxl` (`mukbo_id` ASC) VISIBLE,
  INDEX `FKkfepddltqde0pif3dlrqaupss` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKbkpe37r7hqrg6uu6mpocklqxl`
    FOREIGN KEY (`mukbo_id`)
    REFERENCES `mmm`.`mukbo` (`mukbo_id`),
  CONSTRAINT `FKkfepddltqde0pif3dlrqaupss`
    FOREIGN KEY (`user_id`)
    REFERENCES `mmm`.`users` (`user_id`),
  CONSTRAINT `FKmtoxyhettye5oke0c800xjo0l`
    FOREIGN KEY (`mbti_id`)
    REFERENCES `mmm`.`mbti` (`mbti_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
