package com.spring.mmm.domain.muklogs.event;

public enum MuklogEventType {

    MUKBO_INVITED, MUKBO_EXITED, MUKJUK_ACHIEVE, MUKUS_RECORDED, GROUP_NAME_CHANGED, REP_MUKJUK_CHANGED, MUKBO_NICKNAME_CHANGED,
    MUKBOT_CREATED, MUKBOT_DELETED, MUKBOT_MODIFIED, MUKBO_KICKED, GROUP_IMAGE_CHANGED

}
